--CREAMOS NUESTRA BASE DE DATOS 'tisg_DB'
CREATE DATABASE tisg_DB;

--INDICAMOS QUE BASE DE DATOS USAREMOS
USE tisg_DB;

--CREAMOS LA TABLA 'Usuarios':
CREATE TABLE `tisg_DB`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Username` VARCHAR(30) NULL,
  `Email` VARCHAR(30) NOT NULL,
  `Pass` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

--CREAMOS LA TABLA 'Clientes':
CREATE TABLE `tisg_DB`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Telefono` INT(30) NOT NULL,
  `Actitud` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

--CREAMOS LA TABLA 'Productos'.
CREATE TABLE `tisg_DB`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  'idClientes' INT NOT NULL,
  `Product` VARCHAR(50) NOT NULL,
  `Code` INT NOT NULL,
  `Precio` INT NOT NULL,
PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE `tisg_DB`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idClientes` INT NOT NULL,
  `Producto` VARCHAR(50) NOT NULL,
  `Codigo` INT NOT NULL,
  `Precio` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

USE tisg_DB;
